[application]
name = "teacher-pod"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "TeacherPod | ğŸ™ï¸"

[web.watcher]
watch_path = ["src", "public", "index.html", "../models"]
index_on_404 = true

[web.resource]
style = []
script = [
    '/assets/tailwind.js',
    '/assets/tailwind.config.js',
]

[web.resource.dev]
script = []

[application.tools]
binaryen = { wasm_opt = true }